"""gitea app — installs the Gitea chart on the cicd cluster.

Sources:
  - Install doc:    https://docs.gitea.com/installation/install-on-kubernetes
  - Chart repo:     https://gitea.com/gitea/helm-chart
  - Chart values:   values/gitea.yaml (pinned overrides)

Persistence:
  - The Gitea chart's `persistence` block creates a PVC
    against `proxmox-lvm-thin` (stage 2's StorageClass).
    All repos + LFS + avatars live on that PVC; hostPath is
    never used.

Ingress:
  - We do NOT use the chart's `ingress` block (it's
    Ingress NGINX-shaped). Instead, we apply our own
    `Gateway` + `HTTPRoute` pair via kubectl_runner.apply.
    The Gateway is anchored to GatewayClass=envoy (from
    stage 2's envoy-gateway controller).
  - The hostname is sourced from `catalog.ingress.base_domain`
    (e.g. `example.net` -> `gitea.example.net`).

Admin password lifecycle:
  - Source of truth: /tmp/gitea-admin.pw (mode 0600) on the
    orchestrator host. Generated by the orchestrator on first
    apply; rotation is `vim /tmp/gitea-admin.pw` + re-apply.
  - Vaultwarden master password source: the operator's .env
    in the orchestrator CWD, key VAULTWARDEN__MASTERPASSWORD
    (the same key the vaultwarden-k8s-sync app reads).
    server_url + email come from .env (VAULTWARDEN__SERVERURL,
    CLIENT_EMAIL) overlaid on catalog.vaultwarden.{server_url,
    email} when those are set. No /tmp/vw.pw — the operator's
    .env is the only sanctioned location.
  - Cluster side: the chart's deployment.yaml envFrom
    secretKeyRefs against Secret `gitea-admin-password` in
    namespace `gitea` (keys: username, password) and its
    initContainer runs `gitea admin user change-password`
    on every pod restart when `passwordMode: keepUpdated`.
    So the orchestrator only needs to keep that Secret's
    `password` key in sync with /tmp/gitea-admin.pw; the
    chart syncs Gitea itself.
  - Vaultwarden side: the orchestrator also pushes the
    password to Vaultwarden as a Secure Note with VKS
    custom-fields triple `namespaces=gitea,
    secret-name=gitea-admin-password, secret-key=password`.
    VaultwardenK8sSync reconciles the cluster Secret back
    to that value within one sync interval (~30s). This
    means Vaultwarden must be reachable for `apply` to
    succeed — see `docs/runbooks/setup-vaultwarden-sync.md`.

Pins:
  - chart: oci://docker.gitea.com/charts/gitea:12.0.0
  - image: gitea/gitea:1.26.x (rolling tag)
  - sub-charts: bitnami postgresql + valkey (HA disabled,
    single-replica — we run a single-CP/worker cluster)

Idempotency:
  - helm upgrade --install (default behavior of HelmRunner)
  - kubectl apply --server-side (default behavior of KubectlRunner)
  - cluster Secret write is drift-checked (no-op when
    /tmp/gitea-admin.pw matches the live Secret)
  - Vaultwarden push is dedup-checked (no-op when a cipher
    with the same VKS triple already exists)
"""

from __future__ import annotations

import base64
import os
import secrets
import string
from pathlib import Path
from typing import Any

from ..container import Container
from ..kubectl_runner import KubectlRunner
from . import AppApplyResult, AppPlanResult, AppStatus, register
from .base import BaseApp

# Chart constants used to live here as module-level
# `CHART`, `CHART_VERSION`, `IMAGE_TAG`, `NAMESPACE`,
# `RELEASE`, `DEFAULT_VALUES_FILE`. WP13 moved them
# onto `GiteaApp` as class attributes; the
# `tests/test_app_class_attributes.py` drift test
# pins the values against `shipped.yaml`.

# Admin user / Secret contract.
# The chart's deployment.yaml secretKeyRefs against
# `existingSecret: gitea-admin-password` for both
# GITEA_ADMIN_USERNAME (key=username) and GITEA_ADMIN_PASSWORD
# (key=password). The chart never creates this Secret itself,
# so the orchestrator owns it end-to-end: /tmp/gitea-admin.pw
# → cluster Secret → Vaultwarden Secure Note → VKS reconciles.
ADMIN_USERNAME = "gitea_admin"
ADMIN_SECRET_NAME = "gitea-admin-password"
ADMIN_PASSWORD_FILE = Path("/tmp/gitea-admin.pw")
# 32 chars from a 70-char unambiguous alphabet. The chart's
# `passwordMode: keepUpdated` will run
# `gitea admin user change-password` on every pod restart;
# the password never needs to be human-typeable.
_ADMIN_PASSWORD_ALPHABET = (
    string.ascii_letters + string.digits + "!@#%^*_+-=."
)

# The Gateway/HTTPRoute manifests live in
# `apps/templates/gitea/gateway.yaml` (WP5 —
# moved out of the inline `GATEWAY_MANIFEST`
# constant). The template uses `string.Template`
# syntax (`${var}`), not f-string syntax.


class GiteaApp(BaseApp):
    """BaseApp for the Gitea chart."""

    name = "gitea"
    namespace = "gitea"
    release = "gitea"
    chart = "oci://docker.gitea.com/charts/gitea"
    chart_version = "12.0.0"
    image_version = "1.26.x"
    default_values_file = "values/gitea.yaml"

    # `_values_file` and `_hostname` are inherited from
    # `BaseApp` (WP9). Pre-WP9 each shipped app declared
    # its own private `_values_file` (returning
    # `ctx.repo_root / <module-level constant>`) and
    # `_hostname` (returning `<app_name>.<base>`).
    # Centralizing both on `BaseApp` means a new app
    # inherits the canonical behaviour for free and a
    # future change to the format updates every app at
    # once.

    def plan(
        self, ctx: Container, catalog: dict[str, Any]
    ) -> AppPlanResult:
        host = self._hostname(catalog)
        rendered_values = self._rendered_values_file(ctx)
        return AppPlanResult(
            app_name=self.name,
            would_install=[
                f"helm upgrade --install {self.release} {self.chart} "
                f"--version {self.chart_version} -n {self.namespace} "
                f"--create-namespace -f {rendered_values}",
            ],
            would_apply=[
                f"kubectl apply --server-side -n {self.namespace} "
                f"(Gateway=gitea, HTTPRoute=gitea, host={host})",
                f"kubectl apply --server-side -n {self.namespace} "
                f"Secret={ADMIN_SECRET_NAME} "
                f"(idempotent; written only when password drifted)",
                f"Vaultwarden Secure Note seeded with VKS triple "
                f"namespaces={self.namespace}, secret-name={ADMIN_SECRET_NAME}, "
                f"secret-key=password (idempotent; dedup by triple)",
            ],
            notes=[
                f"image: gitea/gitea:{self.image_version}",
                "persistence: proxmox-lvm-thin PVC (5Gi)",
                f"ingress host: {host}",
                f"rendered-values: ROOT_URL=https://{host}/, "
                f"DOMAIN/SSH_DOMAIN={host}, PROTOCOL=http, "
                f"DISABLE_REGISTRATION=true",
                f"admin password: source-of-truth "
                f"{ADMIN_PASSWORD_FILE} (mode 0600) → "
                f"Secret={ADMIN_SECRET_NAME}/key=password → "
                f"Vaultwarden Secure Note → VKS reconciles. "
                f"Rotation: edit the file, re-apply.",
            ],
        )

    def apply(
        self, ctx: Container, catalog: dict[str, Any]
    ) -> AppApplyResult:
        values = self._values_file(ctx)
        if not values.exists():
            raise FileNotFoundError(
                f"gitea values file not found: {values}. "
                f"Run `make apply` from the proxmox-cicd repo root."
            )
        host = self._hostname(catalog)

        # 1a. Render the orchestrator-injected hostname into
        #     a sibling values file. The committed
        #     `values/gitea.yaml` is a static defaults file
        #     with a `$PUBLIC_HOST` sentinel in
        #     `gitea.config.server.{ROOT_URL,DOMAIN,SSH_DOMAIN}`.
        #     Without substitution the chart would fall back
        #     to its default `http://git.example.com/` and
        #     the rendered app.ini would trip the "Your
        #     ROOT_URL in app.ini is unlikely matching the
        #     site you are visiting" warning at every Gitea
        #     boot. Pattern mirrors the cloudflared app
        #     (`cloudflared-tunnel-remote.values-rendered.yaml`);
        #     sibling convention
        #     `<name>.values-rendered.yaml` is gitignored.
        #     PROTOCOL stays `http` in the committed values
        #     file — the in-pod listener serves plain HTTP
        #     because TLS terminates at the Gateway upstream
        #     and the chart's TLS certs are NOT mounted
        #     inside the pod. Setting PROTOCOL=https here
        #     would make Gitea try to bind HTTPS on :3000
        #     and fail with "Failed to load https cert file".
        #     ROOT_URL (the public-facing scheme, used for
        #     OAuth/email/webhook links) and PROTOCOL (the
        #     in-pod listener scheme) are deliberately
        #     decoupled.
        rendered_values = self._rendered_values_file(ctx)
        rendered_values.parent.mkdir(parents=True, exist_ok=True)
        # Read committed defaults; overlay hostname. We
        # deliberately rewrite the full file rather than
        # appending so that removing a sentinel from the
        # committed values file stops generating output here
        # on the next apply (idempotent over re-runs).
        base_text = values.read_text()
        rendered_text = base_text.replace("$PUBLIC_HOST", host)
        rendered_values.write_text(
            "# Auto-generated by the gitea app at apply-time.\n"
            "# Do not edit — re-runs overwrite.\n"
            "# Gitignored via values/*.values-rendered.yaml.\n"
            + rendered_text
        )
        os.chmod(rendered_values, 0o600)
        ctx.logger.info(
            "gitea.rendered_values_ok",
            path=str(rendered_values.relative_to(ctx.repo_root)),
            public_host=host,
        )

        # 1b. Ensure the admin password lifecycle before
        #     the chart's initContainer runs. We do this
        #     BEFORE helm upgrade --install so that:
        #       - the cluster Secret exists by the time the
        #         chart's deployment.yaml envFrom picks it up
        #       - Vaultwarden holds the cipher before VKS
        #         has a chance to start reconciling
        #
        #     Two steps, both hard-fail on failure
        #     ("Vaultwarden must be working before any app
        #     can install" — the operator's contract):
        #       i.  read-or-generate /tmp/gitea-admin.pw
        #           (canonical operator-side source of truth)
        #       ii. apply the cluster Secret `gitea-admin-password`
        #           (idempotent — only writes on drift)
        #       iii. push the password to Vaultwarden as a
        #            Secure Note (idempotent — dedup by VKS
        #            triple)
        kubectl = self._kubectl(ctx)
        admin_password = self._read_or_generate_admin_password(ctx)
        self._ensure_cluster_admin_secret(ctx, kubectl, admin_password)
        # Overwrite the local variable so a later exception
        # trace doesn't carry the plaintext into log strings.
        try:
            self._seed_admin_password_to_vaultwarden(
                ctx, catalog, admin_password
            )
        finally:
            admin_password = ""

        # 1. helm upgrade --install.
        result = ctx.helm.install_or_upgrade(
            release=self.release,
            chart=self.chart,
            namespace=self.namespace,
            version=self.chart_version,
            values_files=(rendered_values,),
            timeout_s=300.0,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"helm upgrade --install {self.release} failed: "
                f"rc={result.returncode} stderr={result.stderr.strip()[:500]}"
            )
        ctx.logger.info(
            "gitea.helm_install_ok",
            release=self.release,
            chart_version=self.chart_version,
            namespace=self.namespace,
        )

        # 2. Apply Gateway + HTTPRoute via the container's
        # kubectl (so tests can mock it; production gets the
        # real KubectlRunner bound to the sibling proxmox-k3s
        # kubeconfig). kubectl was already built in step 1b.
        # WP5: the manifest now lives in
        # `apps/templates/gitea/gateway.yaml`; rendered via
        # `_render_template` with `${namespace}` + `${host}`.
        manifest = self._render_template(
            "gateway.yaml", namespace=self.namespace, host=host
        )
        apply_result = kubectl.apply(
            manifest=manifest, namespace=self.namespace, server_side=True
        )
        if apply_result.returncode != 0:
            raise RuntimeError(
                f"kubectl apply Gateway/HTTPRoute for gitea failed: "
                f"rc={apply_result.returncode} "
                f"stderr={apply_result.stderr.strip()[:500]}"
            )
        ctx.logger.info(
            "gitea.gateway_applied",
            host=host,
            namespace=self.namespace,
        )

        # 3. Surface the operator-visible next step. The chart
        # has installed + the Gateway is up + the admin
        # password is stored in /tmp/gitea-admin.pw + the
        # cluster Secret + Vaultwarden. All that's left is
        # to log in, create a runner registration token, and
        # (optionally) configure an org. We point the
        # operator at the URL + the canonical login command
        # so they don't have to dig through chart docs.
        ctx.logger.info(
            "gitea.ready_for_config",
            url=f"https://{host}",
            admin_username=ADMIN_USERNAME,
            password_source=f"cat {ADMIN_PASSWORD_FILE}",
            next_step=(
                "log in to the Gitea UI as "
                f"{ADMIN_USERNAME} with the password in "
                f"{ADMIN_PASSWORD_FILE} (cat it). Then create "
                "a runner registration token via "
                "Site Administration -> Actions -> Runners -> "
                "Create new runner; the gitea-runner app's "
                "apply step will mint this token automatically "
                "and store it in Vaultwarden for VKS to "
                "consume."
            ),
        )

        return AppApplyResult(
            app_name=self.name,
            namespace=self.namespace,
            release=self.release,
            chart_version=self.chart_version,
            image_version=self.image_version,
            ingress_host=host,
            next_step=(
                f"log in to https://{host} as {ADMIN_USERNAME} "
                f"with the password in {ADMIN_PASSWORD_FILE} "
                f"(cat it). Rotation: edit {ADMIN_PASSWORD_FILE} "
                f"then `uv run cicdctl apply cicd --app gitea` — "
                f"the orchestrator updates the cluster Secret + "
                f"the Vaultwarden Secure Note, and the chart's "
                f"keepUpdated initContainer syncs Gitea on the "
                f"next pod restart."
            ),
        )

    def destroy(self, ctx: Container, catalog: dict[str, Any]) -> None:
        kubectl = self._kubectl(ctx)
        # helm uninstall the release.
        result = ctx.helm.uninstall(self.release, self.namespace, timeout_s=120.0)
        if result.returncode != 0:
            ctx.logger.warn(
                "gitea.helm_uninstall_failed",
                release=self.release,
                stderr=result.stderr.strip()[:500],
            )
        # Delete the namespace; PVCs are deleted via
        # the StorageClass's reclaim policy (default: Delete).
        del_result = kubectl.delete_namespace(self.namespace, timeout_s=120.0)
        if del_result.returncode != 0:
            ctx.logger.warn(
                "gitea.namespace_delete_failed",
                namespace=self.namespace,
                stderr=del_result.stderr.strip()[:500],
            )
        ctx.logger.info("gitea.destroyed", namespace=self.namespace)

    def status(
        self, ctx: Container, catalog: dict[str, Any]
    ) -> AppStatus:
        host = self._hostname(catalog)

        # helm list -n gitea — does the release exist?
        list_result = ctx.helm.list_releases(namespace=self.namespace, timeout_s=15.0)
        release_present = (
            list_result.returncode == 0 and self.release in list_result.stdout
        )
        chart_version: str | None = self.chart_version if release_present else None
        image_version: str | None = self.image_version if release_present else None

        notes: list[str] = []
        if not release_present:
            notes.append("release not installed; run `cicdctl apply cicd`")
            return AppStatus(
                app_name=self.name,
                namespace=self.namespace,
                release_present=False,
                chart_version=None,
                image_version=None,
                ingress_host=None,
                notes=notes,
            )

        # Release is installed. Probe the Gitea HTTP API via the
        # in-cluster Service so the smoke test works without
        # /etc/hosts and an external DNS resolution. The probe
        # uses kubectl `get --raw` (no port-forward needed) and
        # hits /api/v1/version — a public, unauthenticated
        # endpoint. A 200 means the UI is up and ready for the
        # operator to open https://gitea.<base_domain> in a
        # browser and start configuring the admin user +
        # registering repos.
        kubectl = self._kubectl(ctx)
        probe = kubectl.get(
            resource="svc",
            name="gitea-http",
            namespace=self.namespace,
            jsonpath='{.metadata.annotations.gitea\\.smoke}',
            timeout_s=15.0,
        )
        # Fallback probe: talk to the in-cluster gitea Service
        # via kubectl-run (a one-shot busybox pod). Cheaper than
        # port-forward and works from anywhere the operator can
        # reach the apiserver.
        ready_for_config = self._smoke_gitea_api_ready(kubectl)
        if ready_for_config:
            notes.append(
                "Gitea is running and the HTTP API responds to "
                "/api/v1/version. Open https://gitea.<base_domain> "
                "in a browser to finish first-boot configuration "
                "(set the admin password, register the runner, "
                "create repos)."
            )
        else:
            notes.append(
                "Gitea pods are up but /api/v1/version did not "
                "respond — the init container may still be "
                "running. Re-run `cicdctl status cicd` in a "
                "minute."
            )

        # Suppress unused-variable linter: probe is reserved
        # for future kubectl-only probes.
        _ = probe

        return AppStatus(
            app_name=self.name,
            namespace=self.namespace,
            release_present=True,
            chart_version=chart_version,
            image_version=image_version,
            ingress_host=host,
            notes=notes,
        )

    def _smoke_gitea_api_ready(self, kubectl: KubectlRunner) -> bool:
        """Hit /api/v1/version on the in-cluster gitea Service
        via a one-shot `kubectl run` busybox pod. Returns True
        on HTTP 200, False otherwise. Cheap; doesn't need a
        port-forward or any operator-side tooling.
        """
        # `kubectl run --rm -i --restart=Never --image=...` blocks
        # until the pod exits, so this returns in seconds. We
        # `curl` the cluster-local Service URL and check the
        # exit code (curl returns 0 on 2xx/3xx, 22 on 4xx/5xx).
        result = kubectl.run_oneshot(
            image="curlimages/curl:8.10.1",
            namespace=self.namespace,
            command=[
                "/bin/sh",
                "-c",
                "curl -fsS http://gitea-http:3000/api/v1/version",
            ],
            timeout_s=20.0,
        )
        return result.returncode == 0

    # `_kubectl` and `_kubeconfig` are inherited from
    # `BaseApp` (WP6). Pre-WP6, gitea split kubeconfig
    # resolution into two helpers (one building the
    # `Kubeconfig`, one wrapping it in a `KubectlRunner`)
    # because the orchestrator didn't always supply a
    # runner. With the loader centralized on `BaseApp`,
    # both vanish — `self._kubectl(ctx)` returns the
    # cached runner when present (test paths), or builds
    # one from the per-cluster kubeconfig (production).

    # ------------------------------------------------------------------ #
    # Admin password lifecycle: /tmp/gitea-admin.pw + cluster Secret    #
    # + Vaultwarden Secure Note. Rotation flow: edit the file, re-apply. #
    # ------------------------------------------------------------------ #

    def _read_or_generate_admin_password(self, ctx: Container) -> str:
        """Read the canonical admin password from
        ``/tmp/gitea-admin.pw`` (mode 0600); generate a strong
        random one on first apply and write it back to the
        same file. The file is the operator-side source of
        truth; rotation is just `vim /tmp/gitea-admin.pw` +
        `cicdctl apply cicd --app gitea`.
        """
        if ADMIN_PASSWORD_FILE.exists():
            text = ADMIN_PASSWORD_FILE.read_text().splitlines()
            password = text[0].strip() if text else ""
            if not password:
                raise RuntimeError(
                    f"{ADMIN_PASSWORD_FILE} is empty; remove it "
                    "and re-run to generate a fresh password."
                )
            ctx.logger.info(
                "gitea.admin_password_read",
                path=str(ADMIN_PASSWORD_FILE),
                length=len(password),
            )
            return password

        # First-ever apply on this orchestrator host. Mint a
        # strong random password and persist it; the operator
        # never has to type one in or copy one out of pod logs.
        password = "".join(
            secrets.choice(_ADMIN_PASSWORD_ALPHABET) for _ in range(32)
        )
        ADMIN_PASSWORD_FILE.write_text(password + "\n")
        os.chmod(ADMIN_PASSWORD_FILE, 0o600)
        ctx.logger.info(
            "gitea.admin_password_generated",
            path=str(ADMIN_PASSWORD_FILE),
            length=len(password),
            note=(
                "saved to /tmp/gitea-admin.pw (mode 0600); "
                "rotation: edit the file, re-apply."
            ),
        )
        return password

    def _ensure_cluster_admin_secret(
        self, ctx: Container, kubectl: KubectlRunner, password: str
    ) -> None:
        """Create or update the ``gitea-admin-password`` Secret
        in namespace ``gitea`` with keys ``username`` +
        ``password``. The chart's deployment.yaml envFrom
        secretKeyRefs both keys from this Secret, and its
        initContainer (templates/gitea/init.yaml lines 118-129)
        calls ``gitea admin user change-password`` on every
        pod restart when ``passwordMode: keepUpdated``. So the
        orchestrator's only job is to keep this Secret's
        ``password`` key aligned with /tmp/gitea-admin.pw.

        Idempotent: we read the live Secret first and only
        `kubectl apply` when the password actually drifted.
        """
        live = kubectl.get(
            resource="secret",
            name=ADMIN_SECRET_NAME,
            namespace=self.namespace,
            jsonpath="{.data.password}",
        )
        live_pw = ""
        if live.returncode == 0 and (live.stdout or "").strip():
            try:
                live_pw = base64.b64decode(
                    live.stdout.strip()
                ).decode("utf-8", errors="replace")
            except Exception:
                live_pw = ""
        if live_pw == password:
            ctx.logger.info(
                "gitea.admin_secret_in_sync",
                secret=ADMIN_SECRET_NAME,
                namespace=self.namespace,
            )
            return

        # WP5 — admin-secret manifest moved to
        # `apps/templates/gitea/admin-secret.yaml`.
        # The password is freshly minted (or loaded
        # from disk) at this point; it never lives in
        # a log line or a file outside `/tmp`.
        secret_yaml = self._render_template(
            "admin-secret.yaml",
            secret_name=ADMIN_SECRET_NAME,
            namespace=self.namespace,
            username=ADMIN_USERNAME,
            password=password,
        )
        apply_result = kubectl.apply(
            manifest=secret_yaml,
            namespace=self.namespace,
            server_side=True,
        )
        if apply_result.returncode != 0:
            raise RuntimeError(
                f"kubectl apply Secret={ADMIN_SECRET_NAME} failed: "
                f"rc={apply_result.returncode} "
                f"stderr={apply_result.stderr.strip()[:500]}"
            )
        ctx.logger.info(
            "gitea.admin_secret_written",
            secret=ADMIN_SECRET_NAME,
            namespace=self.namespace,
            action="updated" if live_pw else "created",
        )

    def _seed_admin_password_to_vaultwarden(
        self,
        ctx: Container,
        catalog: dict[str, Any],
        password: str,
    ) -> None:
        """Push the admin password into Vaultwarden as a
        Secure Note with VKS custom-fields triple
        ``namespaces=gitea, secret-name=gitea-admin-password,
        secret-key=password``. VaultwardenK8sSync reconciles
        the cluster Secret back to that value within one sync
        interval (~30s).

        WP12 — thin wrapper over `BaseApp._vaultwarden_client`
        + `BaseApp._seed_vaultwarden_note`. The heavy lifting
        (kubectl.get for VKS BW_CLIENTID/BW_CLIENTSECRET,
        VaultwardenClient.login, idempotent dedup via
        list_ciphers) lives on `BaseApp`; this method only
        supplies the gitea-specific note_name + VKS triple.

        Hard-fails on Vaultwarden unreachable: the operator's
        contract is "VW must be working before any app can
        install". Returns silently if a cipher with the same
        VKS triple already exists (idempotency dedup; mirrors
        cloudflared's behavior — see the 2026-07-14 vault
        audit comment in apps/cloudflared.py).

        Can be disabled for test/CI environments by setting
        ``catalog.vaultwarden.skip_admin_seed: true``. The
        cluster Secret is still written; only the Vaultwarden
        push is skipped. Without this knob the unit tests
        would need a live Vaultwarden to mock around.
        """
        vw_cfg = catalog.get("vaultwarden", {}) or {}
        if vw_cfg.get("skip_admin_seed"):
            ctx.logger.info(
                "gitea.admin_vaultwarden_skipped",
                reason="catalog.vaultwarden.skip_admin_seed=true",
                note="cluster Secret was still written; only the Vaultwarden push is suppressed",
            )
            return

        client = BaseApp._vaultwarden_client(ctx, catalog)
        BaseApp._seed_vaultwarden_note(
            ctx,
            client,
            catalog,
            note_name="gitea k8s admin password",
            body_text=password,
            namespace=self.namespace,
            secret_name=ADMIN_SECRET_NAME,
            secret_key="password",
            app_short="gitea",
        )

    # `_kubeconfig` and `_current_cluster` moved to
    # `BaseApp._kubectl` (WP6).


# Side-effect import: register on import.
register(GiteaApp)


__all__ = ["GiteaApp"]
